# Generated by Django 2.0 on 2017-12-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171219_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='submissions/')),
            ],
        ),
        migrations.AlterField(
            model_name='submissionsreviewer',
            name='status',
            field=models.IntegerField(choices=[(-1, 'submission_not_made'), (0, 'submission_in_review'), (1, 'submission_back_from_review'), (2, 'submission_approved')], default=0),
        ),
        migrations.AlterField(
            model_name='usersubmissions',
            name='status',
            field=models.IntegerField(choices=[(-1, 'submission_not_made'), (0, 'submission_in_review'), (1, 'submission_back_from_review'), (2, 'submission_approved')], default=-1),
        ),
        migrations.AlterField(
            model_name='usersubmissions',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Document'),
        ),
    ]
